version: "2"

services:
  localstack:
    container_name: "Localstack_sku"
    image: localstack/localstack:0.10.6

    ports:
      - "4566:4566"
      - "8082:8082"
    environment:
      - SERVICES=s3:4566
      - HOSTNAME_EXTERNAL=localhost
      - DEBUG=1
      - PORT_WEB_UI=8082
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_SECRET_ACCESS_KEY=KKKKXKKKKXKKKKKKKKKXKKKXKKKKXKKKKXKKKKKKK
      - AWS_ACCESS_KEY_ID=AAAAAAAAAAAAAAAAAAAA
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./localstack/:/docker-entrypoint-initaws.d/
